Update vm.yml

diff --git a/.github/workflows/vm.yml b/.github/workflows/vm.yml
--- a/.github/workflows/vm.yml
+++ b/.github/workflows/vm.yml
@@ -50,10 +50,10 @@ jobs:
           echo "exitcode=$?" >> $GITHUB_OUTPUT
         continue-on-error: true
 
-      - name: Capture Plan Exit Code
-        id: check_plan
-        run: |
-          echo "exitcode=${{ steps.plan.outcome == 'success' && '0' || (steps.plan.outcome == 'failure' && '1' || '2') }}" >> $GITHUB_OUTPUT
+      # - name: Capture Plan Exit Code
+      #   id: check_plan
+      #   run: |
+      #     echo "exitcode=${{ steps.plan.outcome == 'success' && '0' || (steps.plan.outcome == 'failure' && '1' || '2') }}" >> $GITHUB_OUTPUT
       # - name: Comment Terraform Plan on PR (even if push to PR branch)
       #   uses: actions/github-script@v7
       #   if: (steps.plan.outcome == 'success' || steps.plan.outcome == 'failure') && !(github.event_name == 'push' && github.ref == 'refs/heads/main')
@@ -97,11 +97,11 @@ jobs:
       #         body
       #       });
 
-      - name: Fail if Terraform Plan failed (syntax or auth issue)
-        if: steps.plan.outputs.exitcode == '1'
-        run: |
-          echo "❌ Terraform plan failed with exit code 1"
-          exit 1
+      # - name: Fail if Terraform Plan failed (syntax or auth issue)
+      #   if: steps.plan.outputs.exitcode == '1'
+      #   run: |
+      #     echo "❌ Terraform plan failed with exit code 1"
+      #     exit 1
 
       - name: Terraform Apply
         if: github.event_name == 'push' && github.ref == 'refs/heads/main'
